# config of consul server
host: '127.0.0.1'
port: 8500
key: 'tiktok/message_srv'

# message_srv的KV配置
# ``` json
# {
#   "name": "message_srv",
#   "mysql": {
#     "host": "127.0.0.1",
#     "port": 3306,
#     "user": "root",
#     "password": "123456",
#     "db": "tiktok"
#   },
#   "redis": {
#     "host": "127.0.0.1",
#     "port": 6378,
#     "password": "tiktok123"
#   },
#   "msg_encrypt": {
#     "key": "ABCDABCDABCDABCD",
#   },
#   "otel": {
#     "endpoint": ":4317"
#   }
# }
# ```
