// Code generated by Kitex v0.5.2. DO NOT EDIT.
package messageservice

import (
	server "github.com/cloudwego/kitex/server"
	MessageServer "tiktok-demo/shared/kitex_gen/MessageServer"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler MessageServer.MessageService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
